### ISSUE TITLE
Cannot install pyYAHTS because of conflicting dependencies

### ISSUE THREAD

**Issue by seekerquest** [automateyournetwork/pyYAHTS#13]
Hi John,

I tried installing **pyYAHTS** on Cygwin and WSL with different Python versions **(3.10, 3.8, 3.9)** but keep producing the following error:

```shell
ERROR: Cannot install pyyahts==1.0.1, pyyahts==1.0.10, pyyahts==1.0.11, pyyahts==1.0.13, pyyahts==1.0.14, py
yahts==1.0.15, pyyahts==1.0.16, pyyahts==1.0.17, pyyahts==1.0.18, pyyahts==1.0.19, pyyahts==1.0.2, pyyahts==
1.0.20, pyyahts==1.0.3, pyyahts==1.0.4, pyyahts==1.0.5, pyyahts==1.0.6, pyyahts==1.0.7 and pyyahts==1.0.8 be
cause these package versions have conflicting dependencies.

The conflict is caused by:
    pyyahts 1.0.20 depends on pyats[full]==22.1
    pyyahts 1.0.19 depends on pyats[full]==22.1
    pyyahts 1.0.18 depends on pyats[full]==22.1
    pyyahts 1.0.17 depends on pyats[full]==22.1
    pyyahts 1.0.16 depends on pyats[full]==22.1
    pyyahts 1.0.15 depends on pyats[full]==22.1
    pyyahts 1.0.14 depends on pyats[full]==22.1
    pyyahts 1.0.13 depends on pyats[full]==22.1
    pyyahts 1.0.11 depends on pyats[full]==22.1
    pyyahts 1.0.10 depends on pyats[full]==22.1
    pyyahts 1.0.8 depends on pyats[full]==22.1
    pyyahts 1.0.7 depends on pyats[full]==22.1
    pyyahts 1.0.6 depends on pyats[full]==22.1
    pyyahts 1.0.5 depends on pyats[full]==22.1
    pyyahts 1.0.4 depends on pyats[full]==22.1
    pyyahts 1.0.3 depends on pyats[full]<23.0 and >=22.1
    pyyahts 1.0.2 depends on pyats[full]<23.0 and >=22.2
    pyyahts 1.0.1 depends on pyats[full]<23.0 and >=22.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#deal
ing-with-dependency-conflicts
```

Any chance there could be dependency conflict that can be resolved ? can you help with this ?

Thanks!

**Comment by automateyournetwork** [comment]
Thanks for bringing this up - do you have pyATS 22.2+ installed already ? Is that causing the conflict? I had an issue with 22.2 and Genie I am waiting for the pyATS team to fix - here is my dependancy list 

[tool.poetry.dependencies]
python = "^3.10"
rich-click = "^1.2.1"
pyats = {version = "22.1", extras = ["full"]}
json2table = "^1.1.5"
fpdf = "^1.7.2"
pandas = "^1.4.1"
tabulate = "^0.8.9"
rich = "^12.1.0"
networkx = "^2.7.1"
pyvis = "^0.1.9"

In a fresh virtual environment you should by able to pip install pyYAHTS ? Or does this not work? Let me know

**Comment by seekerquest** [comment]
Thank you for such a quick response!!!

i will check my dependencies, compare them to the ones listed and post an update/fix to the issue.

Thanks again!

**Comment by automateyournetwork** [comment]
Thank you! Again try making a fresh virtual env and install pyYAHTS inside
there you shouldn't get any conflicts (I hope)! Appreciate your interest!
